name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@749e2dcbc6735ce0c36e1dbbb660618cd7b5f91c
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "Hello from github actions!"
